name: Deploy to EC2

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.MD'

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04  # 가장 최신의 Ubuntu 러너를 사용합니다.

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18'  # Node.js 버전을 설정합니다.

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Deploy to AWS S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET : ${{secrets.AWS_S3_BUCKET}}
          AWS_DISTRIBUTION_ID : ${{secrets.AWS_DISTRIBUTION_ID}}
          AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
        run: sh deploy/deploy.sh  # 배포 스크립트 실행
